xautoclaim
andymccurdy/redis-py pull request #1529
Opened 2021-07-28 13:58 UTC by AvitalFineRedis

### Pull Request check-list

_Please make sure to review and check all of these items:_

- [ ] Does `$ tox` pass with this change (including linting)?
- [ ] Do the CI tests pass with this change (enable it first in your forked repo and wait for the github action build to finish)?
- [ ] Is the new or changed code fully tested?
- [ ] Is a documentation update included (if this change modifies existing APIs, or introduces new ones)?

_NOTE: these things are not required to open a PR and can be done
afterwards / while the PR is open._

### Description of change

support xautoclaim command

2021-07-28 13:58 UTC, AvitalFineRedis commented
@chayim

2021-07-29 13:52 UTC, chayim commented on redis/client.py
> +        if count is not None:
```suggestion
        if count is not None and not isinstance(count, int)
```

2021-07-29 13:54 UTC, chayim commented
@AvitalFineRedis Instead of force passing ints around - I'd rely on the untyped nature of python. Cast the value of the string to an int and see what happens. Double casting an int in python is effectively free.

2021-07-29 13:54 UTC, chayim requested changes
@AvitalFineRedis Instead of force passing ints around - I'd rely on the untyped nature of python. Cast the value of the string to an int and see what happens. Double casting an int in python is effectively free.

2021-08-05 09:25 UTC, merged