KeyT for set operations
andymccurdy/redis-py pull request #3190
Opened 2024-03-20 18:32 UTC by earonesty

### Description of change

Change set operation key-types to KeyT

https://github.com/redis/redis-py/issues/3189

2024-04-02 12:26 UTC, dvora-h approved these changes

2024-05-15 09:47 UTC, gerzse commented
@earonesty, somehow this PR ended up in conflict state. Could you, please, update it, so we merge it? Thanks!

2025-05-30 08:33 UTC, petyaslavova requested changes

2025-05-30 08:33 UTC, petyaslavova commented on redis/commands/core.py
>          return self.execute_command("SINTERSTORE", dest, *args)
The `dest` argument of `sinterstore` method should also be changed as it represents the name of a new set.
The same applies for `sdiffstore` method's `dest` argument

2025-06-11 07:08 UTC, petyaslavova commented on redis/commands/core.py
>          return self.execute_command("SINTERSTORE", dest, *args)
Done.

2025-06-11 07:08 UTC, petyaslavova approved these changes

2025-06-11 11:00 UTC, merged